apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: k8s-test-node-api-server
          image: andeslam2019/k8s-test-node-api-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DB
              value: "postgresdb"
            - name: DBPASS
              value: "admin123"
            - name: DBHOST
              value: 'db-service' # Same as db.yaml service
            - name: DBPORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - name: expose-service-port
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
